import { FALLBACK_CATEGORY } from './category.types'

export function normalizeLabel(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

// Single-word keywords: matched as whole word (must appear as a standalone token).
// Multi-word keywords: matched as substring in the normalized label.
function matchesKeyword(normalized: string, words: string[], keyword: string): boolean {
  if (keyword.includes(' ')) {
    return normalized.includes(keyword)
  }
  return words.includes(keyword)
}

const EXPENSE_KEYWORDS: Record<string, string[]> = {
  Makanan: [
    'makan',
    'makanan',
    'sarapan',
    'lunch',
    'dinner',
    'brunch',
    'jajan',
    'cemilan',
    'snack',
    'kopi',
    'ngopi',
    'coffee',
    'starbuck',
    'sbux',
    'nasi',
    'mie',
    'mi',
    'bakso',
    'sate',
    'ayam',
    'geprek',
    'padang',
    'warteg',
    'warung',
    'gofood',
    'grabfood',
    'shopeefood',
    'mcd',
    'kfc',
    'cfc',
    'hokben',
    'boba',
    'chatime',
    'menantea',
    'jus',
    'resto',
    'restoran',
    'cafe',
    'kafe',
    'kantin',
    'catering',
    'martabak',
    'gorengan',
    'janji jiwa',
    'fore',
    'tomoro',
    'milk tea',
    'es teh',
  ],
  Transport: [
    'transport',
    'transportasi',
    'bensin',
    'pertalite',
    'pertamax',
    'solar',
    'spbu',
    'gojek',
    'grab',
    'gocar',
    'grabcar',
    'gobike',
    'ojek',
    'ojol',
    'maxim',
    'indrive',
    'tol',
    'etoll',
    'parkir',
    'parking',
    'busway',
    'transjakarta',
    'mrt',
    'lrt',
    'krl',
    'kereta',
    'travel',
    'damri',
    'bus',
    'angkot',
    'taksi',
    'taxi',
    'bluebird',
    'e-toll',
  ],
  Belanja: [
    'belanja',
    'shopping',
    'beli',
    'groceries',
    'grocery',
    'supermarket',
    'minimarket',
    'indomaret',
    'alfamart',
    'alfamidi',
    'superindo',
    'hypermart',
    'transmart',
    'shopee',
    'tokopedia',
    'tokped',
    'lazada',
    'blibli',
    'zalora',
    'baju',
    'celana',
    'sepatu',
    'sandal',
    'tas',
    'fashion',
    'uniqlo',
    'hm',
    'zara',
    'skincare',
    'makeup',
    'kosmetik',
    'sephora',
    'watson',
    'guardian',
    'tiktok shop',
  ],
  Tagihan: [
    'tagihan',
    'bayar',
    'bill',
    'listrik',
    'pln',
    'pdam',
    'internet',
    'wifi',
    'indihome',
    'biznet',
    'pulsa',
    'kuota',
    'telkomsel',
    'xl',
    'indosat',
    'tri',
    'smartfren',
    'byu',
    'bpjs',
    'asuransi',
    'insurance',
    'cicilan',
    'kredit',
    'kpr',
    'leasing',
    'angsuran',
    'iuran',
    'langganan',
    'subscription',
    'netflix',
    'spotify',
    'disney',
    'icloud',
    'chatgpt',
    'canva',
    'figma',
    'adobe',
    'token listrik',
    'first media',
    'myrepublic',
    'paket data',
    'youtube premium',
    'google one',
  ],
  Hiburan: [
    'hiburan',
    'nonton',
    'bioskop',
    'cinema',
    'xxi',
    'cgv',
    'cinepolis',
    'game',
    'games',
    'steam',
    'genshin',
    'topup',
    'diamond',
    'konser',
    'concert',
    'festival',
    'event',
    'karaoke',
    'ktv',
    'billiard',
    'liburan',
    'wisata',
    'hotel',
    'traveloka',
    'airbnb',
    'gym',
    'fitness',
    'yoga',
    'spa',
    'pijat',
    'massage',
    'mobile legend',
    'kolam renang',
    'tiket pesawat',
    'top up',
  ],
  Kesehatan: [
    'kesehatan',
    'dokter',
    'klinik',
    'puskesmas',
    'apotek',
    'apotik',
    'obat',
    'vitamin',
    'suplemen',
    'periksa',
    'checkup',
    'vaksin',
    'gigi',
    'behel',
    'kacamata',
    'optik',
    'kimia farma',
    'century',
    'rumah sakit',
    'tes darah',
    'dokter gigi',
  ],
  Pendidikan: [
    'pendidikan',
    'sekolah',
    'kuliah',
    'kampus',
    'spp',
    'ukt',
    'les',
    'kursus',
    'bimbel',
    'buku',
    'seminar',
    'webinar',
    'training',
    'sertifikasi',
    'udemy',
    'alat tulis',
  ],
  Transfer: [
    'transfer',
    'kirim',
    'tf',
    'patungan',
    'donasi',
    'sedekah',
    'zakat',
    'infaq',
    'amplop',
    'angpao',
    'kirim uang',
    'bayar utang',
    'bayarin',
    'split bill',
    'kado',
    'sumbangan',
  ],
}

const INCOME_KEYWORDS: Record<string, string[]> = {
  Gaji: ['gaji', 'gajian', 'salary', 'payroll', 'thr'],
  Bonus: ['bonus', 'komisi', 'insentif', 'tunjangan', 'reward', 'cashback', 'refund', 'reimburse'],
  'Transfer Keluarga': [
    'mama',
    'mami',
    'ibu',
    'bunda',
    'papa',
    'papi',
    'ayah',
    'bapak',
    'ortu',
    'kakak',
    'adik',
    'om',
    'tante',
    'keluarga',
    'orang tua',
  ],
  Hadiah: ['hadiah', 'kado', 'dapet', 'menang', 'giveaway', 'gift', 'angpao', 'amplop'],
  'Side Income': [
    'freelance',
    'project',
    'proyek',
    'jualan',
    'dagang',
    'endorse',
    'affiliate',
    'fee',
    'honor',
    'royalti',
    'dividen',
    'bunga',
    'sampingan',
    'sidejob',
    'online shop',
    'olshop',
  ],
  Pacar: ['pacar', 'ayang', 'sayang', 'bebeb', 'gebetan'],
}

function matchCategory(label: string, dict: Record<string, string[]>): string {
  const normalized = normalizeLabel(label)
  const words = normalized.split(' ')

  for (const [category, keywords] of Object.entries(dict)) {
    for (const keyword of keywords) {
      if (matchesKeyword(normalized, words, keyword)) {
        return category
      }
    }
  }
  return FALLBACK_CATEGORY
}

export function suggestExpenseCategory(label: string): string {
  if (!label.trim()) return FALLBACK_CATEGORY
  return matchCategory(label, EXPENSE_KEYWORDS)
}

export function suggestIncomeCategory(label: string): string {
  if (!label.trim()) return FALLBACK_CATEGORY
  return matchCategory(label, INCOME_KEYWORDS)
}
